package cs505.group1.state;

/**
 * An abstract framework for developing and using contexts in a finite state machine
 * to set actions generated by a GrovePi button sensor.
 * @author CS505 Fall17 Group1: <br>
 * Emily Park<br>
 * Jeffrey Blankenship  <br>
 * Cecelia Oluwadoyinsola<br>
 * James Luczynski<br>
 * Melissa Mulcahy <br>
 * @version 2017.10.29
 */
public abstract class ButtonContext {
 
    //No javadoc provided: private visibility.
    //This instance variable stores the current buttonState.
    private ButtonState buttonState;
    
    /**
     * Constructs a newly allocated ButtonContext object that represents the specified buttonState.
     * 
     * @param buttonState sets the initial value of buttonState.
     */
    protected ButtonContext(ButtonState buttonState){
        this.buttonState = buttonState;
    }
    
    /**
     * Implements code for a single button press.
     */
    public abstract void singlePress();
    
    /**
     * Implements code for a double button press.
     */
    public abstract void doublePress();
    
    /**
     * Implements code for a long button press.
     */
    public abstract void longPress();
    
    /**
     * Sets the state to be equal to the passed state.
     * @param buttonState The state to be set.
     */
    public abstract void setState(ButtonState  buttonState);
    
    /**
     * Gets the current state.
     * @return ButtonState
     */
    public abstract ButtonState getState();
    
    /**
     * Invokes the toString method of the concrete class for the
     * current state.  
     */
    public abstract String toString();
    
}
